### PR TITLE
Add dn-m bump

### LINKED ISSUE #41: Implement bump version
- Update product version (Xcode build configuration)
- `git tag ...`
- `git push origin tag ...`
- `carthage build --no-skip-current`
- `carthage archive`

### PR DESCRIPTION
**Pull request by mossheim**
Closes #41.

Usage:
1. export environment variable GITHUB_TOKEN, an auth token (or set it via -t in the call)
2. From the root of the working tree, run `dn-m bump [-Mmpb] [-d <description>] [-n <name>] [--[no-]archive] [-t <token>]`

Flags:
-M: major version increment
-m: minor
-p: patch
--no-archive: don't attempt to create a carthage archive and upload
-d: provide a description for the release (default is "Release version $version")
-b: mark this as a prerelease/beta
-n: set the name of the release (default is $tag)

What it does:
- Computes the next tag
- Creates it locally and on GitHub
- Creates a release on GitHub
- (optional) creates a carthage archive and uploads it to the release as an asset
- if any step fails, deletes the tags locally and remotely, if applicable

TODO: ?? I left some TODOs in the code. What other features do you want @jsbean ?

### CODE REVIEW

**Comment by mossheim** [comment]
Forgot to mention, I used this tool to create these releases:

https://github.com/dn-m/Collections/releases
https://github.com/dn-m/Helper/releases

via `dn-m bump -p -b`
and `dn-m bump -m -b -d "Test description" --no-archive`
respectively

**Comment by mossheim** [comment]
@jsbean I think this is now pretty robust in features. I'm going to work on cleaning up other parts of Helper now.

**Comment by jsbean** [comment]
This looks amazing. I think I am hitting one snag, though.

I am attempting in `dn-m/ArithmeticTools`. This repository is deprecated for dn-m purposes, but is used for Hans' project. 

The latest release is: `0.18.1`. I run `dn-m bump -m`, with the expected next release being `0.19(.0)`. Instead, it creates `0.10`. It then provides an error: `Could not add tag`.

I wonder if there is an issue in the checking newest tag numerically?

**Comment by mossheim** [comment]
@jsbean - that's so weird. When I run it locally, I get the correct result:

```
[brianheim@BrianMBP ArithmeticTools]$ ../Helper/dn-m bump -m
Creating local tag 0.19.0
Creating remote tag 0.19.0
```

Is that perhaps because you've got an old commit checked out? Should it always just figure out whatever the most recent tag is and bump that?

**Comment by mossheim** [comment]
Oh, I realize what it is now. You've tagged that commit as both 0.18.1 _and_ 0.9.3. Is this something I should protect against?

**Comment by mossheim** [comment]
`git tag --points-at <ref>` will list all the tags pointing to \<ref>. So, I think what I have to do is `git describe` to get the most recent tag, then `git tag --points-at <tag>` to get any other tags at that same tag, then do resolution to find the highest tag. Another option would be to fail if multiple candidates are found, and provide a `-v` option that lets you explicitly name the tag to use. `-v` might be useful in the long run as well (for creating sub-patch versions, etc.). What do you think?

**Comment by jsbean** [comment]
"You've tagged that commit as both 0.18.1 and 0.9.3". Oh jeeze, then :/. That sounds incredibly dumb, but is obviously a potential issue.

I would say, default to the newest of multiple candidates. Otherwise, observe what is sent through a `-v` command. However, I would say, implement the default first, then expose the `-v` option second.

**Comment by mossheim** [comment]
With new changes (and a bunch of extra fake tags):
```shell
[brianheim@BrianMBP ArithmeticTools]$ ../Helper/dn-m bump --version-only -m
Multiple tags found:
	0.18.1
	0.9.3
	1.3.7
	1.9.3
	NOT_A_TAG
Resolved to 1.9.3
New version would be 1.10.0
```

`--version-only` was a testing idea, but I think it's worth leaving in, similar to the `--dry-run` option on several git commands.

**Pull request closed without merging**
